name: Daily Commit

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 02:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Timestamp (23f1000625@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date -u)" > last_run.txt

      - name: Commit and Push Changes (23f1000625@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f1000625@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit: $(date -u)"
          git push
